package dao.mapper;

import dao.model.DrawLog;
import dao.model.DrawLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DrawLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    int countByExample(DrawLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    int deleteByExample(DrawLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer drawLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    int insert(DrawLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    int insertSelective(DrawLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    List<DrawLog> selectByExample(DrawLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    DrawLog selectByPrimaryKey(Integer drawLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DrawLog record, @Param("example") DrawLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DrawLog record, @Param("example") DrawLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DrawLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DrawLog record);
}