package dao.model;

import java.util.ArrayList;
import java.util.List;

public class DrawLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    public DrawLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDrawLogIdIsNull() {
            addCriterion("draw_log_id is null");
            return (Criteria) this;
        }

        public Criteria andDrawLogIdIsNotNull() {
            addCriterion("draw_log_id is not null");
            return (Criteria) this;
        }

        public Criteria andDrawLogIdEqualTo(Integer value) {
            addCriterion("draw_log_id =", value, "drawLogId");
            return (Criteria) this;
        }

        public Criteria andDrawLogIdNotEqualTo(Integer value) {
            addCriterion("draw_log_id <>", value, "drawLogId");
            return (Criteria) this;
        }

        public Criteria andDrawLogIdGreaterThan(Integer value) {
            addCriterion("draw_log_id >", value, "drawLogId");
            return (Criteria) this;
        }

        public Criteria andDrawLogIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("draw_log_id >=", value, "drawLogId");
            return (Criteria) this;
        }

        public Criteria andDrawLogIdLessThan(Integer value) {
            addCriterion("draw_log_id <", value, "drawLogId");
            return (Criteria) this;
        }

        public Criteria andDrawLogIdLessThanOrEqualTo(Integer value) {
            addCriterion("draw_log_id <=", value, "drawLogId");
            return (Criteria) this;
        }

        public Criteria andDrawLogIdIn(List<Integer> values) {
            addCriterion("draw_log_id in", values, "drawLogId");
            return (Criteria) this;
        }

        public Criteria andDrawLogIdNotIn(List<Integer> values) {
            addCriterion("draw_log_id not in", values, "drawLogId");
            return (Criteria) this;
        }

        public Criteria andDrawLogIdBetween(Integer value1, Integer value2) {
            addCriterion("draw_log_id between", value1, value2, "drawLogId");
            return (Criteria) this;
        }

        public Criteria andDrawLogIdNotBetween(Integer value1, Integer value2) {
            addCriterion("draw_log_id not between", value1, value2, "drawLogId");
            return (Criteria) this;
        }

        public Criteria andDrawIpIsNull() {
            addCriterion("draw_ip is null");
            return (Criteria) this;
        }

        public Criteria andDrawIpIsNotNull() {
            addCriterion("draw_ip is not null");
            return (Criteria) this;
        }

        public Criteria andDrawIpEqualTo(String value) {
            addCriterion("draw_ip =", value, "drawIp");
            return (Criteria) this;
        }

        public Criteria andDrawIpNotEqualTo(String value) {
            addCriterion("draw_ip <>", value, "drawIp");
            return (Criteria) this;
        }

        public Criteria andDrawIpGreaterThan(String value) {
            addCriterion("draw_ip >", value, "drawIp");
            return (Criteria) this;
        }

        public Criteria andDrawIpGreaterThanOrEqualTo(String value) {
            addCriterion("draw_ip >=", value, "drawIp");
            return (Criteria) this;
        }

        public Criteria andDrawIpLessThan(String value) {
            addCriterion("draw_ip <", value, "drawIp");
            return (Criteria) this;
        }

        public Criteria andDrawIpLessThanOrEqualTo(String value) {
            addCriterion("draw_ip <=", value, "drawIp");
            return (Criteria) this;
        }

        public Criteria andDrawIpLike(String value) {
            addCriterion("draw_ip like", value, "drawIp");
            return (Criteria) this;
        }

        public Criteria andDrawIpNotLike(String value) {
            addCriterion("draw_ip not like", value, "drawIp");
            return (Criteria) this;
        }

        public Criteria andDrawIpIn(List<String> values) {
            addCriterion("draw_ip in", values, "drawIp");
            return (Criteria) this;
        }

        public Criteria andDrawIpNotIn(List<String> values) {
            addCriterion("draw_ip not in", values, "drawIp");
            return (Criteria) this;
        }

        public Criteria andDrawIpBetween(String value1, String value2) {
            addCriterion("draw_ip between", value1, value2, "drawIp");
            return (Criteria) this;
        }

        public Criteria andDrawIpNotBetween(String value1, String value2) {
            addCriterion("draw_ip not between", value1, value2, "drawIp");
            return (Criteria) this;
        }

        public Criteria andDrawContentIsNull() {
            addCriterion("draw_content is null");
            return (Criteria) this;
        }

        public Criteria andDrawContentIsNotNull() {
            addCriterion("draw_content is not null");
            return (Criteria) this;
        }

        public Criteria andDrawContentEqualTo(Integer value) {
            addCriterion("draw_content =", value, "drawContent");
            return (Criteria) this;
        }

        public Criteria andDrawContentNotEqualTo(Integer value) {
            addCriterion("draw_content <>", value, "drawContent");
            return (Criteria) this;
        }

        public Criteria andDrawContentGreaterThan(Integer value) {
            addCriterion("draw_content >", value, "drawContent");
            return (Criteria) this;
        }

        public Criteria andDrawContentGreaterThanOrEqualTo(Integer value) {
            addCriterion("draw_content >=", value, "drawContent");
            return (Criteria) this;
        }

        public Criteria andDrawContentLessThan(Integer value) {
            addCriterion("draw_content <", value, "drawContent");
            return (Criteria) this;
        }

        public Criteria andDrawContentLessThanOrEqualTo(Integer value) {
            addCriterion("draw_content <=", value, "drawContent");
            return (Criteria) this;
        }

        public Criteria andDrawContentIn(List<Integer> values) {
            addCriterion("draw_content in", values, "drawContent");
            return (Criteria) this;
        }

        public Criteria andDrawContentNotIn(List<Integer> values) {
            addCriterion("draw_content not in", values, "drawContent");
            return (Criteria) this;
        }

        public Criteria andDrawContentBetween(Integer value1, Integer value2) {
            addCriterion("draw_content between", value1, value2, "drawContent");
            return (Criteria) this;
        }

        public Criteria andDrawContentNotBetween(Integer value1, Integer value2) {
            addCriterion("draw_content not between", value1, value2, "drawContent");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table draw_log
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table draw_log
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}