package dao.model;

public class DrawLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_log.draw_log_id
     *
     * @mbggenerated
     */
    private Integer drawLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_log.draw_ip
     *
     * @mbggenerated
     */
    private String drawIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_log.draw_content
     *
     * @mbggenerated
     */
    private Integer drawContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_log.draw_log_id
     *
     * @return the value of draw_log.draw_log_id
     *
     * @mbggenerated
     */
    public Integer getDrawLogId() {
        return drawLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_log.draw_log_id
     *
     * @param drawLogId the value for draw_log.draw_log_id
     *
     * @mbggenerated
     */
    public void setDrawLogId(Integer drawLogId) {
        this.drawLogId = drawLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_log.draw_ip
     *
     * @return the value of draw_log.draw_ip
     *
     * @mbggenerated
     */
    public String getDrawIp() {
        return drawIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_log.draw_ip
     *
     * @param drawIp the value for draw_log.draw_ip
     *
     * @mbggenerated
     */
    public void setDrawIp(String drawIp) {
        this.drawIp = drawIp == null ? null : drawIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_log.draw_content
     *
     * @return the value of draw_log.draw_content
     *
     * @mbggenerated
     */
    public Integer getDrawContent() {
        return drawContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_log.draw_content
     *
     * @param drawContent the value for draw_log.draw_content
     *
     * @mbggenerated
     */
    public void setDrawContent(Integer drawContent) {
        this.drawContent = drawContent;
    }
}